Make docs.rs include futures functionality
rustwasm/gloo pull request #116
Opened 2020-04-30 12:49 UTC by derekdreery

Make docs.rs builds include the futures feature.

2021-06-11 03:05 UTC, DesmondWillowbrook commented
What is blocking the merging of this pull request?

2021-06-22 17:07 UTC, hamza1311 requested changes

2021-06-22 17:07 UTC, hamza1311 commented on crates/file/src/lib.rs
> +//! 2. a `Future` API.
I don't think this is correct anymore. Can you rebase master onto your branch or merge master into it and then update the READMEs?

2021-06-23 18:21 UTC, hamza1311 commented
Nevermind, I did that myself

2021-06-23 18:22 UTC, merged