Html head access
rustwasm/gloo pull request #179
Opened 2021-12-17 08:50 UTC by Madoshakalaka

closes #175

2021-12-17 08:53 UTC, Madoshakalaka commented
PR is contaminated by some previous merged commits. They don't add anything extra.

2021-12-20 09:46 UTC, hamza1311 requested changes

2021-12-20 09:46 UTC, hamza1311 commented on crates/utils/src/lib.rs
> +/// Convenience function to access the head lement.
```suggestion
/// Convenience function to access the head element.
```

2021-12-20 09:47 UTC, hamza1311 approved these changes
LGTM

2021-12-20 09:52 UTC, merged