Add `TryFrom<web_sys::WebSocket>`
rustwasm/gloo pull request #365
Opened 2023-08-10 13:03 UTC by mokeyish

On server side, websocket may create from WebSocketPair. So we need `TryFrom<web_sys::WebSocket>`.

https://docs.rs/worker/latest/src/worker/websocket.rs.html#26-31

2023-08-11 16:17 UTC, hamza1311 requested changes
Thanks for the PR! I'm in favor of adding a way to use an existing web socket instance. There's one comment that about accessing the inner instance that need to be addressed

2023-08-11 16:17 UTC, hamza1311 commented on crates/net/src/websocket/futures.rs
> +
Please remove this impl. We don't want to allow such easy access to the inner WebSocket instance. See the discussion at https://github.com/rustwasm/gloo/pull/337 for more details about why that is the case.

2023-08-11 19:38 UTC, hamza1311 approved these changes
Thanks

2023-08-11 19:39 UTC, merged

2023-09-03 06:36 UTC, carlsverre commented
@hamza1311 is it possible to ship this sometime soon? I would prefer not to pin a git sha